title = "process_data server"
scene = "process_data"
[logging]
level = "info"
  [logging.file]
  filename = "process_data.server.log"
  path = "/data0/process_data/logs"
  file_name_date_format = "20060102.150405"
  file_name_date_align = true
  rotation_count = 3


[kafka_consumer]
routines = 2
channel_buffer_size = 1000
brokers = ["127.0.0.1:9092"]
topics = ["test1"]
groupid = "process_data"
auto_offset_reset = "latest" # earliest or latest


[worker]
routines = 64
log_file_num = 100
log_file_Path = "/data0/process_data_log/pvlog/"
# log_file_path must end with "/"
# file_path_example: "/data0/process_data_log/pvlog/2019-01-13/01/39_pvlog.txt"


#redis
[redis_cluster]
name = "redis_cluster"
database = 0
hasher = "REMAINDER"
max_idle = 5
max_active = 0
max_retry = 0
idle_timeout = "5m0s"
dial_connect_timeout = "1s"
dial_read_timeout = "1s"
dial_write_timeout = "100ms"
[[redis_cluster.redis_node]]
    address = "127.0.0.1:6379"



